#config_version=6

mode:
  start_events: ball_started
  stop_events: ball_will_end
  priority: 1000

config:
  - light_player.yaml

slide_player:
  mode_base_started:
    base:
      action: play
  mode_base_started.1:
    attract:
      action: remove

sound_player:
  s_start_active:
    cash:
      ducking: &duck_effects
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s

event_player:
  mode_base_started:
    - mode_start_priority_shows

timed_switches:
  ts_start_button:
    time: 3000ms
    switches:
      - s_start
